targets:
  finger_gang:
    sources:
      include:
        - lib/**       
        - pubspec.*
        - $package$
      exclude:
        - lib/**/generated/**
        - packages/**
    builders:
      source_gen:combining_builder:
        enabled: true
        options:
          ignore_for_file:
            - implicit_dynamic_parameter
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.g.dart'
      json_serializable:
        options:
          field_rename: snake
          checked: true
          explicit_to_json: true
      freezed:
        enabled: true
        options:
          copy_with: true
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generated/{{file}}.freezed.dart'
global_options:
  freezed:freezed:
    runs_before:
      - build_resolvers:transitive_digests